server:
  port: 8090

logging:
  level:
    org.springframework.security: trace
    org.springframework.web: trace


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000