server:
  port: 9000

logging:
  level:
    org.springframework.security: trace
    org.springframework.web: trace

spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        issuer: "http://auth-server:9000"

